### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by 9527-csroad** [LocalJoost/YoloHolo#1]
Hi, thanks for your nice job. Could you write a simple usage?

**Comment by LocalJoost** [comment]
Have you read this? https://localjoost.github.io/HoloLens-AI-using-Yolo-ONNX-models-to-localize-objects-in-3D-space/

**Comment by 9527-csroad** [comment]
I'm sorry to reply to you too late. There are some problems while opening the project, click "continue"-"Ignore" can open the project. Thanks for your wonderful work.
