### ISSUE TITLE
Execution in unity 

### ISSUE THREAD

**Issue by AmokraneIlhem** [LocalJoost/YoloHolo#2]
Hi, thanks for this great work!
As I'm trying to test YOLO in unity, i imported the project and added the model.onnx as you mentioned it. However, when I run it under unity nothing happens.
 Please, what should I do to make the detection work? 
Thank u in advance.

**Comment by LocalJoost** [comment]
My dear friend. It only works when running in a HoloLens 2

**Comment by AmokraneIlhem** [comment]
Thank you for your answer. Do you have any idea how to make YOLO work in unity by activating the camera?

**Comment by LocalJoost** [comment]
Well Image detection works fine, only after it has found stuff it tries to locate it in space using the depth camera and Unity doesn't have a Spatial Map inside the editor

**Comment by AmokraneIlhem** [comment]
Indeed, I'm looking to deploy a deep learning model more precise EfficientPose under unity to estimate the 3D position of an object for a mobile application, but I have no idea on the deployment on unity therefore, I wanted to try with YOLO since I saw through my research that it was deployed and tested already and it worked.
